version: "3.7"

services:

  postgres:
    container_name: postgres
    image: postgres:10.10
    restart: always
    env_file: .env
    volumes:
      - db_volume:/var/lib/postgresql
    ports:
      - "5432:5432"

  app:
    build: ./translation_app
    container_name: translation_app
    depends_on:
      - postgres
    restart: always
    env_file: .env
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

volumes:
  db_volume: