version: "3.7"

services:

  db:
    container_name: postgres
    image: postgres:10.10
    restart: always
    env_file: .env
    volumes:
      - db_volume:/var/lib/postgresql
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend
    env_file: .env
    depends_on:
      - db
    restart: always
    expose:
      - 5000

  nginx:
    build: ./nginx
    container_name: nginx
    env_file: .env
    restart: always
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"


  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - npm_config_unsafe_perm=true
    expose:
      - "8080"

volumes:
  db_volume: